package org.acme.models.cobranca;

public enum Status {
        PENDING,CONFIRMED,RECEIVED,RECEIVED_IN_CASH,OVERDUE,REFUND_REQUESTED
        ,REFUNDED,CHARGEBACK_REQUESTED,CHARGEBACK_DISPUTE,AWAITING_CHARGEBACK_REVERSAL,DUNNING_REQUESTED
        ,DUNNING_RECEIVED,AWAITING_RISK_ANALYSIS
        ,CANCELLED,DONE,
}
